### ISSUE TITLE
Stopped working since February

### ISSUE THREAD

**Issue by Keralin** [scribd/datadog_backup#153]
Hey! 

First of all thanks for this fantastic app I have been using it for almost 2 years and it's great :)

Just letting you know if I'm the only one with this issue, I have been using the tool as a cronjob from Kubernetes everything has worked as expected since February started to fail, and it looks like something related to the way we auth on Datadog, I only have those traces failing when authenticate.

```bash
datadog_backup backup --debug
I, [2023-04-04T11:15:44.659689 #68]  INFO -- : Starting diffs on 10 threads
/usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/core.rb:119:in `with_200': Request failed with error ["403", {"status"=>"error", "code"=>403, "errors"=>["Forbidden"], "statuspage"=>"http://status.datadoghq.eu", "twitter"=>"http://twitter.com/datadogops", "email"=>"support@datadoghq.com"}] (RuntimeError)
	from /usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/core.rb:57:in `get_all'
	from /usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/dashboards.rb:6:in `all_boards'
	from /usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/dashboards.rb:25:in `backup'
	from /usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/cli.rb:28:in `each'
	from /usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/cli.rb:28:in `backup'
	from /usr/local/bundle/gems/datadog_backup-1.1.3/lib/datadog_backup/cli.rb:139:in `run!'
	from /usr/local/bundle/gems/datadog_backup-1.1.3/bin/datadog_backup:94:in `<top (required)>'
	from /usr/local/bundle/bin/datadog_backup:25:in `load'
	from /usr/local/bundle/bin/datadog_backup:25:in `<main>'
```
I was using the 1.1.3 version so I decided to update to the stable version(3.2.1) and occurs the same:

```bash
datadog_backup backup --debug
I, [2023-04-04T10:57:41.261480 #14]  INFO -- : Starting diffs on 10 threads
D, [2023-04-04T10:57:41.261839 #14] DEBUG -- request: GET https://api.datadoghq.eu/api/v1/dashboard
D, [2023-04-04T10:57:41.261868 #14] DEBUG -- request: DD-API-KEY:[REDACTED]
Traceback (most recent call last):
	19: from /usr/local/bundle/bin/datadog_backup:23:in `<main>'
	18: from /usr/local/bundle/bin/datadog_backup:23:in `load'
	17: from /usr/local/bundle/gems/datadog_backup-3.2.1/bin/datadog_backup:92:in `<top (required)>'
	16: from /usr/local/bundle/gems/datadog_backup-3.2.1/lib/datadog_backup/cli.rb:89:in `run!'
	15: from /usr/local/bundle/gems/datadog_backup-3.2.1/lib/datadog_backup/cli.rb:28:in `backup'
	14: from /usr/local/bundle/gems/datadog_backup-3.2.1/lib/datadog_backup/cli.rb:28:in `each'
	13: from /usr/local/bundle/gems/datadog_backup-3.2.1/lib/datadog_backup/dashboards.rb:12:in `backup'
	12: from /usr/local/bundle/gems/datadog_backup-3.2.1/lib/datadog_backup/dashboards.rb:7:in `all'
	11: from /usr/local/bundle/gems/datadog_backup-3.2.1/lib/datadog_backup/resources.rb:60:in `get_all'
	10: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/connection.rb:200:in `get'
	 9: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/connection.rb:444:in `run_request'
	 8: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/rack_builder.rb:153:in `build_response'
	 7: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/middleware.rb:17:in `call'
	 6: from /usr/local/bundle/gems/faraday-retry-2.1.0/lib/faraday/retry/middleware.rb:149:in `call'
	 5: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/response/logger.rb:23:in `call'
	 4: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/middleware.rb:17:in `call'
	 3: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/middleware.rb:17:in `call'
	 2: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/response.rb:42:in `on_complete'
	 1: from /usr/local/bundle/gems/faraday-2.7.4/lib/faraday/middleware.rb:18:in `block in call'
/usr/local/bundle/gems/faraday-2.7.4/lib/faraday/response/raise_error.rb:20:in `on_complete': the server responded with status 403 (Faraday::ForbiddenError)
```
     
I did not modify any credentials or rotate them so that's why I'm asking if you know something related to this problem 😄 
Meanwhile, I have opened a ticket to datadog to see if they made some changes.

**Comment by Keralin** [comment]
After some manual fixes and some app keys deprecated I have found that the issue was with the app key that was deleted manually and with a new app key and API key everything worked again as expected, sorry for the noise!

Closing the issue since everything works as expected 😄
